# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a-4782N8nEDKUFaXHtSU4zwgX-JLdQWF
"""



pip install insta-scrape

from instascrape.scrapers import comment
from instascrape import Post

post = Post("https://www.instagram.com/p/Ct4XZJxNsXV/")

post.scrape()

comments = post.get_recent_comments()

for comment in comments:
  print(f"{comment.username} - {comment.text}")